### ISSUE TITLE
`freeze` adds a cold SLOAD on all interactions

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/universal-rewards-distributor#14]
# Context

https://github.com/morpho-org/universal-rewards-distributor/blob/426ad7969840e82a76df24fd4eb5a7d2378accd4/src/UniversalRewardsDistributor.sol#L183-L189

The frozen status could be signaled using the zero root: `require(rootOf[distributionId] != bytes32(0), ErrorsLib.FROZEN);`

Replacing the cold SLOAD with a warm SLOAD at most

**Comment by julien-devatom** [comment]
I love this idea. Consequently, `Frozen` naming is not explicit anymore, `ErrorsLib.EMPTY_ROOT` is probably better suited.

**Comment by Rubilmax** [comment]
> We must not enforce `forceUpdateRoot` from happening only when it's frozen then

Why not?

Btw, I think `owner` should be able to submit a root without the timelock duration

**Comment by MerlinEgalite** [comment]
Else it's a 2 step process to change the root which is annoying

**Comment by Rubilmax** [comment]
> Else it's a 2 step process to change the root which is annoying

What I see is that with the current design, in order for the owner to update a root, they have to:
1. `freeze(true)`
2. `forceUpdateRoot`
3. `freeze(false)`

With the design I suggest, this process is now only 2 steps:
1. `freeze`
2. `forceUpdateRoot`

Which is strictly better than the previous design

I assume you're suggesting bringing down this process to a single step for the owner: `forceUpdateRoot`, but I don't see why we **must** do this

**Comment by MerlinEgalite** [comment]
> The frozen status could be signaled using the zero root: require(rootOf[distributionId] != bytes32(0), ErrorsLib.FROZEN);

In the design you suggest the freezing would happen by force updating the root no? Else, how do you set the root to the zero root?

**Comment by Rubilmax** [comment]
There are multiple ways of freezing then:
1. call `freeze` which just sets the root to 0
2. `forceUpdateRoot` indeed if we remove the check that it's frozen first

I think having a dedicated function for it has added value

**Comment by MerlinEgalite** [comment]
> There are multiple ways of freezing then:
> 
> 1. call `freeze` which just sets the root to 0
> 2. `forceUpdateRoot` indeed if we remove the check that it's frozen first
> 
> I think having a dedicated function for it has added value (clarity? single-purpose?) and we could check for a non-zero submitted root when force update or submitting a root

But in the case `freeze` overrides the root is completely at odd with the single-purpose principle.

My fear is that this suggestion brings more confusion in the code than anything unless we agree on the following spec: "when the owner freezes a distribution the root must be reset the zero root".

**Comment by julien-devatom** [comment]
You can go ahead and check my implementation of removing the freeze function. 
Single-purpose is more for a function than a variable (for example, you will always use ` owner = address(0)` for an ownerless distribution instead of providing a `uint256 => bool ownerless` mapping; it makes no sense. This is the same for the frozen state IMO)

There is still a difference: a root submitter can always propose roots even if the main root is 0, where the frozen state prevents new root submissions. 
You can always recreate the previous frozen state by removing all root submitters.
