### ISSUE TITLE
`claim` system could be designed another way

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/universal-rewards-distributor#15]
# Context

The current `claim` design requires:
1. Proposing a treasury (as owner)
2. Accepting the treasury (as the treasury)
3. At each root update, increasing the allowance of the treasury to the URD (as the treasury)
4. Pull tokens from the treasury on each `claim` (as the URD)

While it could be designed the following way:
1. Set a treasury (as owner ; no need to accept)
2. At each root update, approve the URD (as the treasury)
3. At each root update, call URD.transfer to pull tokens & perform internal accounting (as the treasury)

In the second design, internal accounting is necessary because the URD is designed as a singleton

## Pros

- treasury can't disallow the URD (thus mess up a distribution) anymore: only the owner can retrieve remaining reward tokens by submitting the Merkel root that distributes everything to themself

## Cons

- 1 more accounting variable (instead of the ERC20's allowance)
- treasury must have reward tokens upfront

Design 2 can be more interesting in systems where the treasury may contain other funds than the reward tokens  which quantity evolves through time (e.g. in singletons or ERC4626 vaults)

**Comment by julien-devatom** [comment]
For the third step, the treasury has to allow the tokens, so the problem is the same, you still have to increase your allowance at each root update.

**Comment by Rubilmax** [comment]
> For the third step of the suggested design, the treasury has to allow the tokens, so the problem is the same, you still have to increase your allowance at each root update.

What problem are you referring to?
I am suggesting design 2 because it removes 1 step required from the treasury: step 2 in design 1. I have never argued that any other problem is solved, and I am convinced that step 2 from design 1 is unnecessary in design 2

> Moreover, the step 3 call is not URD.transfer, but rather `ERC20.transferFrom(treasury, address(this), amount)` and should be done in the update root function. You cannot leverage the ERC20 transfer function since you cannot add logic on a direct transfer.

Indeed, it's the reason I named it `URD.transfer`: it's not a call to the `ERC20` but rather directly to the `URD`, which pull tokens and performs internal accounting (see how step 3 in design 2 explicits this)

> and should be done in the update root function

I'm not sure it **should** be done there, but I agree it **can** be done there and is elegant!

> Moreover, all ERC20 transferred directly to the URD are lost forever (like in a lending contract). So you still have to maintain an allowance somewhere.

This is an interesting point that I didn't think of, because a treasury may not want to lose its reward tokens

**Comment by Rubilmax** [comment]
So this discussion highlighted that in any case (whatever the design), the treasury is required to implement a specific behavior to approve and/or transfer reward tokens from the treasury to the URD. This could be abstracted to some kind of a hook that is called each time a root is updated:

```solidity
  function onRootUpdate(uint256 distributionId) external virtual;
```

which responsibility is to pull reward tokens from the source to the treasury and approve the URD of the amount pulled

**Comment by julien-devatom** [comment]
This solution destroys the advantage of the singleton: you can no longer have a 0 deployment distribution creation.

**Comment by Rubilmax** [comment]
> You can also notice that, even if we are using a transfer, the owner can always withdraw all the funds by submitting a Merkle tree, which transfers all remaining tokens to itself (or to the treasury). It is the same behavior provided by setting the allowance to zero. 

Correct! I'm updating the issue description to have this noted. Then design 2 is ok?

**Comment by Rubilmax** [comment]
> This solution destroys the advantage of the singleton: you can no longer have a 0 deployment distribution creation, and it looks more complex that creating a Treasury proxy holding tokens.

We can have this hook optional, so we have best of both worlds!
