### ISSUE TITLE
Treasury can rug users of a distribution

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/universal-rewards-distributor#23]
# Context

Because the URD relies on reward tokens allowances, treasury can at any time revoke the allowance or spend reward tokens, effectively rugging users that have not yet claimed from a distribution

In the case of vaults that need to redistribute reward tokens to its users, it requires the vault manager to update the allowance of the vault to the URD every epoch, to the exact amount of reward tokens re-distributed (no more else it may conflict with idle supply if the vault's underlying asset is the reward asset, no less else it would revert for last claiming users)

This can be mitigated by:
1. using an escrow contract; OR
2. requiring the treasury to transfer reward tokens upfront

# Thoughts

2 implies the treasury no longer has to accept being a treasury and the URD can just expect to be called to transfer reward tokens each time a root is updated, but the URD needs to perform internal accounting because the URD is a singleton

Or the URD could be a factory that provides easy deployments of individual distributor contracts, requiring reward tokens to be transferred upfront to these distributor contracts each time a root is updated

Coupled with #18, it would make vaults completely autonomous once set up:
```solidity
function redistribute(address distributor, ...) external onlyOwner {
  address redistributor = factory.deploy(...);
  distributor.setReceiver(redistributor); // tokens claimed on behalf of this vault will be transferred to redistributor directly
}
```

**Comment by Rubilmax** [comment]
Before debating on the possible solution, let's just debate whether having the treasury being able to rug is actually an issue

Note that for vaults that need to redistribute reward tokens for example, relying on reward tokens allowances requires to trust the vault manager to approve exactly the amount of reward tokens redistributed after a root update (no more else it may conflict with idle supply if the vault's underlying asset is the reward asset, no less else it would revert for last claiming users)

**Comment by pakim249CAL** [comment]
I don't think this is an actual problem. If any transfer fails from the URD, the affected parties are limited to the claimers from the specific treasury of the specific reward. I believe that solution 1 is a good mitigation for this, and it's probably best practice to reserve funds in an escrow contract rather than approve from a multisig, and it doesn't come with the downside of limiting how rewards can be distributed from the treasuries.

**Comment by Rubilmax** [comment]
I assume you are referring to:

> it requires the vault manager to update the allowance of the vault to the URD every epoch, to the exact amount of reward tokens re-distributed (no more else it may conflict with idle supply if the vault's underlying asset is the reward asset, no less else it would revert for last claiming users)

And my answer is:

> why allowance to urd cannot be a public function?

Because in the case of vaults, `idle` may not be easy to calculate (and in some cases, impossible without a dedicated internal accounting in the said vault)

**Comment by julien-devatom** [comment]
It can be a tradeoff to account for the idle amount. I don't have any design in mind with idle amount, but it seems to be mandatory to have an internal accounting just to separate rewards & idle (since claiming means accruing the ERC20 balance of the vault)

**Comment by Rubilmax** [comment]
Closing this as it seems everyone is ok with the design that trusts all parties involved (treasury, owner & updater)
