### ISSUE TITLE
Rename `transferDistributionOwnership` to `setOwner`

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/universal-rewards-distributor#27]
First, removing distribution would harmonize with: https://github.com/morpho-org/universal-rewards-distributor/blob/426ad7969840e82a76df24fd4eb5a7d2378accd4/src/UniversalRewardsDistributor.sol#L167

Second, it would reduce verbosity.

Else we add distribution in both cases? But for now I think this is a little bit inconsistent.

**Comment by julien-devatom** [comment]
maybe `setDistributionOwner`? I think it's important to mention that this is the owner of a distribution in the function name.

**Comment by MerlinEgalite** [comment]
I agree it's better
