### ISSUE TITLE
`distributionId` -> `id` 

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/universal-rewards-distributor#3]
To make things less verbose

**Comment by julien-devatom** [comment]
It was my first choice, but it was a bit misleading, is it a rootId, distributionId? 

We can find an alternative, such as `distribId`

Chatgpt is not really helpful, though..
![image](https://github.com/morpho-org/universal-rewards-distributor/assets/61523188/0f9061e2-4f04-4eaa-b42e-5420874aea61)

**Comment by MerlinEgalite** [comment]
Thx chat GTP 🥲

Don't you think it's clear enough? What would be a rootId btw?

**Comment by julien-devatom** [comment]
Nothing in reality, but usually, when we think about a distribution contract, we have only one level of depth: the roots, Roots are contained in distribution (+1 depth), and generally, I prefer having a more explicit naming (for code readability)

For us, it's clear that a distribution is a set of roots, treasury, owner, timelock, but is it clear for all readers? having more explicit naming introduces the distribution naming. 

I'm not sure it is a good tradeoff: a variable of 14 chars length (not so long) versus reducing readability.
