### ISSUE TITLE
URD could be EIP-2771 compliant

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/universal-rewards-distributor#42]
To enable meta-txs (sponsored rewards claim, for example for ERC4626 vaults that need to distribute reward tokens back to users)
It may be overkill, but always worth asking

**Comment by julien-devatom** [comment]
The `claim` function is public and everyone can claim on behalf, so the only use case is to transfer tokens to another address right? I don't think that it is a required feature for the URD
