### ISSUE TITLE
Should `UniversalRewardsDistributor` inherit `Ownable`?

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/universal-rewards-distributor#44]
Related topic: do we want to prevent being able to renounce ownership of a distribution?

**Comment by MerlinEgalite** [comment]
> Related topic: do we want to prevent being able to renounce ownership of a distribution?

It's already possible no?

**Comment by Rubilmax** [comment]
Currently, the owner can be set to `address(0)`

**Comment by Rubilmax** [comment]
Actually renouncing ownership cannot be prevented: the owner can always transfer ownership to some dead address

**Comment by MerlinEgalite** [comment]
I'm fine with it on my side. Must be acknowledge at least

**Comment by Rubilmax** [comment]
Yes, why not use `Ownable` though? So we don't have to acknowledge anything (it is known that `Ownable` always enable renouncing ownership)

**Comment by MerlinEgalite** [comment]
Ok so maybe we should add a comment to prevent the classic "no 2-step ownership transfer". I'm totally fine with OZ ownable

**Comment by julien-devatom** [comment]
Ownable is transferring ownership to the sender in the constructor, where we want to have the initial owner into the constructor parameters. 
We can transferOwnership right after construction but it'll emit events twice and adds computation

```solidity
    constructor() {
        _transferOwnership(_msgSender());
    }
```

**Comment by Rubilmax** [comment]
Indeed, this is a limit to standard `Ownable`...

**Comment by julien-devatom** [comment]
> Reopening since with OZ v5.0 we don't have the issue mentioned above I think

Youre right. However, now I'm against making changes to the codebase that are refactoring working logic, specially because the code is under audit.

**Comment by Rubilmax** [comment]
`Ownable` was audited internally by OpenZeppelin (we can argue it's been for years considering the minimal changes of v5)
Whereas our own way of managing `owner` was hand-crafted and audited by Spearbit (only, as of today)

So I disagree: we should switch to OZ's `Ownable` v5 just because it's standardized

**Comment by MerlinEgalite** [comment]
Yes yes I agree. It's more for a next iteration, I would keep the issue open

**Comment by Rubilmax** [comment]
Besides, this issue was re-opened following #82 so it's a joke if we decide not to inherit OZ's `Ownable` v5 whereas we are fixing an edge-case we didn't think about we rewriting it...

**Comment by julien-devatom** [comment]
> Besides, this issue was re-opened following #82 so it's a joke if we decide not to inherit OZ's `Ownable` v5 whereas we are fixing an edge-case we didn't think about when rewriting it: emitting the owner at construction 🤡

I do not agree, it was a design choice to not emit event in constructor for default value, and owner is not impacted by this PR.

**Comment by julien-devatom** [comment]
> Besides, this issue was re-opened following #82 so it's a joke if we decide not to inherit OZ's `Ownable` v5 whereas we are fixing an edge-case we didn't think about when rewriting it: emitting the owner at construction 🤡

It make sense

**Comment by julien-devatom** [comment]
One other point: the PR #86 is downgrading to 8.19, whereas Ownable forces ^0.8.29
