### ISSUE TITLE
`OwnerSet` and `TimelockSet` are not emitted at construction

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/universal-rewards-distributor#51]

**Comment by julien-devatom** [comment]
It was a design choice since the factory is emitting everything. 

There is still the case of people not going through the factory, where the initial parameters can be entered manually off-chain (or by using the transaction data, or any other way)

I do not have a strong opinion on that

**Comment by Rubilmax** [comment]
That's an interesting case, because it seems that both an event logged from the factory and from the created contract have usecases
And it seems that for the root, we're emitting it from the factory as well as the contract

Considering the ridiculous gas cost, I'd go for emitting it from both locations
