### ISSUE TITLE
[protocol review] Remove double hashing

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/universal-rewards-distributor#71]
When verifying a proof, the leaves value is hashed twice:
https://github.com/morpho-org/universal-rewards-distributor/blob/26388ed651c0d774d74c1335c104b4a11718e3bd/src/UniversalRewardsDistributor.sol#L120

This is not necessary, we can hash only once safely

**Comment by julien-devatom** [comment]
I agree that there is no security issue by hashing only once in our case. However, if we want to leverage on the oz merkle tree computation library, we have to hash twice

**Comment by QGarchery** [comment]
Oh ok I didn't know this was done by the OZ library, we can close this then

**Comment by julien-devatom** [comment]
Mentionned in #85

**Comment by QGarchery** [comment]
> Mentioned in #85

Closing this then
