### ISSUE TITLE
[protocol review] Events are not reliably emitted for the pending root updates

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/universal-rewards-distributor#74]
Notably the `_setRoot` function does not emit an event when it resets the pending root is deleted, whereas the `revokeRoot` function does emit an event

**Comment by QGarchery** [comment]
I have an idea for a refactor, I will link a PR shortly

**Comment by MerlinEgalite** [comment]
To close no?

**Comment by QGarchery** [comment]
It will be fixed by #83. More precisely see https://github.com/morpho-org/universal-rewards-distributor/pull/83#issuecomment-1790933395

**Comment by julien-devatom** [comment]
Merged so I close it
