### ISSUE TITLE
[protocol review] Provide a unified interface, including structs getter

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/universal-rewards-distributor#76]
See the [similar issue on MM](https://github.com/morpho-org/metamorpho/issues/216) for more details.
For this particular case, we could consider simpler solutions:
1. flattening the PendingRoot struct, which is not used for packing anyway.
2. having one custom getter, and putting the visibility of the faulty `pendingRoot` variable to internal

**Comment by julien-devatom** [comment]
I'm in favor of taking the same decision that the one of mm & blue. Let's wait for an agreement

**Comment by QGarchery** [comment]
Right now the consensus seems to be in favor of having 2 interfaces used: one for static typing, and the other for external use. See the [PR on morpho-blue](https://github.com/morpho-org/morpho-blue/pull/567), and the [PR on metamorpho](https://github.com/morpho-org/metamorpho/pull/272)

**Comment by QGarchery** [comment]
Fixed in #91
