### ISSUE TITLE
[protocol review] Put comments in the interface

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/universal-rewards-distributor#77]
[Similar issue on MM](https://github.com/morpho-org/metamorpho/issues/247).

Should we put comments in the `IUniversalRewardsDistributor` interface instead of directly in the contract ?

@Rubilmax said: "As an integrator, I copy-paste interfaces. I think it's best to have them in the interface, which is what we decided for Blue"

**Comment by julien-devatom** [comment]
Counter argument: as a code reader, I read the implementation, not the interface, to understand the behavior in depth.

Generally it is really frustrating when you are going through the code and you have no direct access to natspecs. However, putting natspecs in interface seems to be the state of the art for natspecs

**Comment by MerlinEgalite** [comment]
Feel free to reopen if you want

**Comment by Rubilmax** [comment]
In all other repositories we moved comments to the interface
Why would this repository be different?
