### ISSUE TITLE
[protocol review] Suggestion for documentation change

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/universal-rewards-distributor#78]
Here is a list of suggestion to improve the documentation:
- [ ] 1. There is no skim function for the owner, which is useful if the rewards have ended and some users have not claimed (and will not be able to claim in the future). Document that it can be done through the Merkle tree
- [ ] 2. The README feels outdated at times. In particular there are mentions of a treasury and allowances. It would be nice to document the purpose of the timelock: it is a layer of safety against badly set updaters, which can be fixed by disabling the faulty updaters and revoking their submissions
- [x] 3. (optional) The claimed mapping is the only mapping that uses named keys (`account`, `reward` and `amount`). For consistency we can remove those, but at the same time they are pretty useful to document them and not mistake `account` with `reward`

**Comment by julien-devatom** [comment]
>  1. There is no skim function for the owner, which is useful if the rewards have ended and some users have not claimed (and will not be able to claim in the future). Document that it can be done through the Merkle tree

You can set a merkle tree that is sending rewards to you

**Comment by julien-devatom** [comment]
> 2. The README feels outdated at times. In particular there are mentions of a treasury and allowances. It would be nice to document the purpose of the timelock: it is a layer of safety against badly set updaters, which can be fixed by disabling the faulty updaters and revoking their submissions

Yes you're right, sorry about that

**Comment by julien-devatom** [comment]
>  3. (optional) The claimed mapping is the only mapping that uses named keys (account, reward and amount). For consistency we can remove those, but at the same time they are pretty useful to document them and not mistake account with reward

Already discussed [here](https://github.com/morpho-org/universal-rewards-distributor/pull/57/files#r1342758573). Imo its important to precise the path clearly since there is a depth mapping with 2 addresses.

**Comment by QGarchery** [comment]
> You can set a merkle tree that is sending rewards to you

Yes, but it is not straightforward and not obvious at first

> Document that it can be done through the Merkle tree

**Comment by julien-devatom** [comment]
Fixed in [this](https://github.com/morpho-org/universal-rewards-distributor/pull/85/commits/f6c2572154de3497b35b06eaf1185c2bce2f1010) commit
