### ISSUE TITLE
Implement simple refactors from protocol review

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/universal-rewards-distributor#88]
See #79 

Todo:
- [ ] [put each sentence in its own line](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374803280)
- [ ] [redirect to foundry installation](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374804125)
- [ ] [remove installation of dependency, and update CI](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374804470)
- [ ] [remove comment about similarity to Morpho rewards distributor](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374804902)
- [ ] [capitalize "Merkle" everywhere](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374805147)
- [ ] [rename "expired" into "elapsed" for the timelock](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374805554)
- [ ] [renaming in the claim function](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374807285)
- [ ] [remove mention of expired proof in errors](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374810717)
- [ ] [reorder interface to match contract](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374811916)
- [ ] [slightly improve test coverage](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374818902)
- [ ] [replace `bytes.concat` with `abi.encode`](https://github.com/morpho-org/universal-rewards-distributor/pull/79#discussion_r1374837549)

**Comment by julien-devatom** [comment]
Some of them are still up to date

**Comment by julien-devatom** [comment]
I close the issue since: 
- the code is frozen from the audit
- lot of suggestions are already implemented
- code is deployed & used in prod.
